### ISSUE TITLE
ExpandablePageView does not resize to fit its content size when initialPage > 0

### ISSUE THREAD

**Issue by egaga** [Limbou/expandable_page_view#15]
Having `ExpandablePageView` with `estimatedPageSize` that is smaller than the height of the actual content, and `PageController` that has `initialPage > 1` correctly navigates to `initialPage` but the content below `estimatedPageSize` is cut off. If `initialPage = 0` this problem does not happen.

I have found only one way to fix through the `ExpandablePageView` interface: namely calling ` controller.notifyListeners()` after the widget has been rendered once. (That method is marked for test-usage only.)

```dart
  @override
  void initState() {
    super.initState();
    controller = PageController(
        initialPage: widget.initialPage,
        keepPage: false,
    );

    WidgetsBinding.instance!.addPostFrameCallback((_) {
      // XXX: Hack
      // When ExpandablePageView is initialized, it does not properly resize to the actual
      // content size, but stays at estimatedPageSize. That could lead to cut content without user noticing.
      // This forces ExpandableView to resize.
      controller.notifyListeners();
    });
  }
  ```

This is a serious bug, as we had a table of rows that is cut off and user even doesn't know there should be more content.

The content is inside a Material `Scaffold -> SingleChildScrollView -> Column -> Custom wrapper` hierarchy.

Sorry that I don't have a reproduceble code right now. I just thought I'd at least inform you of this possibility even if it might not be applicable in every widget hierarchy.

**Comment by egaga** [comment]
I had `1.0.5` version. Upgrading to `1.0.6` fixed the problem, it seems.
Probably this was the fix of the culprit.

Sorry for the disturbance.

**Comment by diezep** [comment]
That fix doesn't work if you are using dynamic pages, only updates the first time i think. 
https://user-images.githubusercontent.com/38699812/164947248-ba9aed30-6916-4c1b-b8b8-e59e1a73f545.mov

I delete the line where ```_previousPage``` is assigned and i changed it for getter function like this:

```
  int get _previousPage => _currentPage - 1 < 0 ? 0 : _currentPage - 1;
```

I think now is fixed.
https://user-images.githubusercontent.com/38699812/164947289-80741bdc-bd54-4f54-975d-aa8ff594cae1.mov

**Comment by egaga** [comment]
@diezep Great that you noticed it, but sorry, currently not working on related stuff. 
I think you should create a PR and see what the maintainers think?
