### ISSUE TITLE
Vertical Axis

### ISSUE THREAD

**Issue by uujiguu** [Limbou/expandable_page_view#16]
Not really a bug or issue but it's is possible to do axis change? If its possible can you add it to package me and other people facing same problem will be appreciate it.

**Comment by Limbou** [comment]
Hi @uujiguu I believe ExpandablePageView has a `scrollDirection` property. Does it solve your problem?

**Comment by jlnrrg** [comment]
If the `scrollDirection` property works like it does with the regular PageView, this should work.
Unfortunately there is no such property as of version `1.0.7`.

**Comment by elkhalifte** [comment]
@Limbou the package does not contain this property 
-v 1.0.7

**Comment by Limbou** [comment]
@uujiguu @jlnrrg @elkhalifte Requested paremeter should now be available starting from version `1.0.8`
