### ISSUE TITLE
Dynamic height children

### ISSUE THREAD

**Issue by Martibis** [Limbou/expandable_page_view#3]
If I have dynamic height children (in my case Text), this doesn't seem to work (it seems to collapse the entire pageview, then un-collapses).

**Comment by Limbou** [comment]
Hi @Martibis, could you provide a short video with the problem and code available to reproduce the bug?

**Comment by Martibis** [comment]
```
ExpandablePageView(
        controller: _controllerp,
        itemCount: _s.length,
        itemBuilder: (BuildContext context, int index) {
          return ReadMoreText(_s[index].experience, trimMode: TrimMode.Line);
        },
      ),
```

https://user-images.githubusercontent.com/13279066/108631423-376a4980-746a-11eb-9527-1ecdb7255010.mp4

**Comment by Limbou** [comment]
This issue has a very similar problem to [this issue](https://github.com/Limbou/expandable_page_view/issues/5) which already has proposed solution. Let's keep the conversation there.
