### ISSUE TITLE
Horizontal expandable not working

### ISSUE THREAD

**Issue by SeriousMonk** [Limbou/expandable_page_view#32]
Hello,
When I set scrollDirection to Axis.horizontal I would expect the PageView to expand automatically horizontally depending on the child's width. 

Am I doing something wrong or does ExpandablePageView only expand vertically to accomodate children?

Thanks

**Comment by Limbou** [comment]
Hi @SeriousMonk, thank you for your question. Currently ExpandablePageView only supports expanding for horizontal axis. Support for vertical axis is coming soon.

**Comment by SeriousMonk** [comment]
Thank you! I'll be patiently waiting then :)

**Comment by Limbou** [comment]
Hi @SeriousMonk I can happily announce that support for vertical scroll direction was added. You can see how it looks in action in the update [Readme](https://github.com/Limbou/expandable_page_view/blob/main/README.md) file and also inside the [example](https://github.com/Limbou/expandable_page_view/tree/main/example) project 🎉
