### ISSUE TITLE
Support animating the size difference between pages

### ISSUE THREAD

**Issue by xinran-finch** [Limbou/expandable_page_view#47]
I'm trying to animate the size of the `ExpandablePageView` when children have different height. Wrapping `ExpandablePageView` with a `AnimatedSize` doesn't work for some reason (it just jumps directly to the new height without animation). Is there a workaround for this?

**Comment by Limbou** [comment]
Hi @xinran-finch, `ExpandablePageView` has `animationDuration` and `animationCurve` parameters, would they work for you? If not, please describe your problem more precisely, ideally with some code example included.
