### ISSUE TITLE
RenderViewport does not support returning intrinsic dimensions. With PageView / ExpandablePageView vertical scroll directions

### ISSUE THREAD

**Issue by Turbozanik** [Limbou/expandable_page_view#48]
Hi, I am not sure this issue is related to your library.
But as I am not sure, I will share it here.

I have described the issue here: 
https://stackoverflow.com/questions/74053907/renderviewport-does-not-support-returning-intrinsic-dimensions-with-pageview

Basically, 
Combination of a `SingleChildScrollView `+ `IntrinsicHeight `+ `PageView `or `ExpandablePageView `along side with `scrollDirection: Axis.vertica`l results in a **RenderViewport does not support returning intrinsic dimensions and I can't understand how to fix this**.

And I would be greatful if you could take a look and tell me if you have any ideas.

**Comment by Limbou** [comment]
Hi @Turbozanik, could you please describe your use case a little bit? `ExpandablePageView` resizes itself to match the height of a currently displayed child and this is what it was designed for, there is currently no way to make it resize to the biggest of all children and keep that size. One reason for that is there would be no way to implement such behavior for `.builder` constructor, as size of all children is never known as they are built dynamically as you scroll through the PageView.

**Comment by Turbozanik** [comment]
Hi @Limbou, at this point I am ok with the fact that `ExpandablePageView` resizes itself to match the height of a currently displayed child, I can set a min height to the container, so it would not shake on child change.

The major issue is that when `ExpandablePageView` is placed in an other `ScrollableWidget` with the **same scroll direction**, it seems like it can't find it's size.
`ExpandablePageView` has `Infinite Size` right(?) and `ScrollView` has `Infinite Size`. This way flutter refuses to render it.
If i will set scrollDirection of outer  `ScrollableWidget` to vertical and `ExpandablePageView` to horizontal it will work, but as soon as I set both of them to vertical, app crashes.

After updaiting to flutter 3.3.10 error has changed from **RenderViewport does not support returning intrinsic dimensions** to **RenderBox was not laid out: RenderPointerListener#41872 NEEDS-LAYOUT NEEDS-PAINT**

Let me show how it all works.

https://user-images.githubusercontent.com/7550948/210228901-1336818f-2f81-4f1c-b718-96d5df5164b6.mp4

As you can see, placing an `Expandable PageView` into another `Scrollable Widget` with the same scroll direction causes app to crash.

Maybe you have any ideas on how we can fix this?

**Comment by Limbou** [comment]
@Turbozanik `ExpandablePageView.builder`, the same way as `ListView.builder` builds its children dynamically, meaning it will only render children that are about to be visible on the screen and disposes of children that are no longer visible on the screen. This makes it impossible for that page view to tell what size it is, therefore it is impossible to put it inside another scroll view with the same axis. You can try to replace my widget with flutter's official `ListView.builder` and you will encounter the same error. 

I believe the only way to have a vertical page view inside a vertical scroll view is to give it a static size, something like this:

```dart
SingleChildScrollView(
      child: Column(
        children: [
          SizedBox(
            height: 200,
            child: ExpandablePageView(
              children: [
                const AvailableBalanceTile(),
                const CardsTile(),
                const ContactsTile(),
              ],
            ),
          ),
          HideCardsButton(),
          const SizedBox(height: 24),
        ],
      ),
    );
```
