### ISSUE TITLE
Way to show a border of the next for the user know that can do a lateral scroll

### ISSUE THREAD

**Issue by fabiomlferreira** [Limbou/expandable_page_view#49]
This extension works very well but it's hard to the end user to know that can do a lateral scroll, one good solution is we have an option to show the some pixels from the next screen.

Something like this
<img width="409" alt="image" src="https://user-images.githubusercontent.com/1872297/201973956-0c47c724-628d-426f-826f-6e2ecb606a6c.png">

**Comment by Limbou** [comment]
Hi @fabiomlferreira, have you tried using a `PageController` with `viewportFraction` parameter set to a non-zero value? Something like this:

```dart
final PageController pageController = PageController(viewportFraction: 0.2);

return ExpandablePageView.builder(
  controller: pageController,
  ...
);
```
