### ISSUE TITLE
Animation firing when the widget first appears

### ISSUE THREAD

**Issue by proninyaroslav** [Limbou/expandable_page_view#5]
This is clearly visible when you open the window or after Hot Restart. In my app, I use a nested structure of `Column` and `Row` inside the `ExpandablePageView` and when the window is first opened (when the widget tree rendering is done), the `Column` height is animated at the speed of `animationDuration`. This is logical, because the `Column` changes its size from `0` px to `N` px. This is not a bug because it's in the logic of the `ExpandablePageView` widget (tween from previous height to the current), but this behavior for the first page in the `PageView`, that appears immediately after the widget tree is created, is clearly undesirable.

What do you think about that? One of the options: animate the size of the page when the page is scrolled, otherwise set the size of the page in the `PageView` without animation. This will also allow to place widgets inside the `ExpandablePageView` that already have a size animation (for example, `ExpansionTile`) and this animation may be inconsistent, i.e. the child's resize animation occurs before the `ExpandablePageView` animation. I have already encountered this, you you can check this behavior.

I created a special example in which I increased the animation duration for clarity and put the `ExpandablePageView` in a separate window. 

https://user-images.githubusercontent.com/7840559/108893964-bdc98b80-7622-11eb-9639-4131392755cd.mp4

```Dart
import 'package:expandable_page_view/expandable_page_view.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: OutlinedButton(
          child: Text('Press me'),
          onPressed: () {
            Navigator.of(context).push(
              MaterialPageRoute(
                builder: (context) => _ExpandablePage(),
              ),
            );
          },
        ),
      ),
    );
  }
}

class _ExpandablePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('ExpandablePageView'),
      ),
      body: SingleChildScrollView(
        child: Column(
          children: [
            ExpandablePageView(
              animationDuration: const Duration(seconds: 1),
              children: [
                ExamplePage(Colors.blue, "1", 300),
                ExamplePage(Colors.green, "2", 400),
                ExamplePage(Colors.red, "3", 500),
              ],
            ),
            const SizedBox(height: 20),
            Text("UNDER PAGE VIEW WIDGET"),
          ],
        ),
      ),
    );
  }
}

class ExamplePage extends StatelessWidget {
  final Color color;
  final String text;
  final double height;

  const ExamplePage(this.color, this.text, this.height);

  @override
  Widget build(BuildContext context) {
    return Container(
      height: height,
      color: color,
      child: Center(
        child: Text(text),
      ),
    );
  }
}
```

**Comment by proninyaroslav** [comment]
A quick fix that works: https://github.com/proninyaroslav/expandable_page_view/tree/animation_fix
This may not be a very pretty solution, but it animates the page widget only when needed, that is, when the page changes. The rest of the time, any resizing of the page widget will not be animated. If this solution suits you, I will make a pull request.

I also checked this with `ExpansionTile` inside `ExpandablePageView`, now only `ExpansionTile` is animating as it should.

**Comment by proninyaroslav** [comment]
Also video confirmation:


https://user-images.githubusercontent.com/7840559/108978915-28b6a900-769b-11eb-926c-ef4bda4ed242.mp4

**Comment by proninyaroslav** [comment]
By the way, another solution: leave the implicit animation of page sizes as an option. By default, it will be disabled, that is, the page animation will only be on scrolling.

**Comment by Limbou** [comment]
Hi @proninyaroslav Thanks for the fix suggestion. I will take a look at it later this week since I am very low on time lately.

**Comment by Limbou** [comment]
I've created a pull request including your fix @proninyaroslav : [PR](https://github.com/Limbou/expandable_page_view/pull/6).

I have also added an additional `estimatedPageSize` variable which could help reduce the problem with shrinking and expanding of page view when you switch pages and they are expensive to build.

I think this PR also fixes the other [issue](https://github.com/Limbou/expandable_page_view/issues/3)
