### ISSUE TITLE
Change of Copyright notice

### ISSUE THREAD

**Issue by lubovtorina** [Limbou/expandable_page_view#51]
Hello!
Could you change Copyright notice in your MIT License (software expandable_page_view) and add the author's name and surname, bacause the author's nickname "Limbou" can be changed in the future and this can make it difficult to identify the copyright owner of your software.
Thank you in advance!

**Comment by lubovtorina** [comment]
@Limbou, ping

**Comment by Limbou** [comment]
Hi @lubovtorina, thank you for pointing that out. License has been updated. I will close this issue, if you have any additional questions please let me know.
