### ISSUE TITLE
Changing the children count (in StatefulWidget)  throws RangeError exception

### ISSUE THREAD

**Issue by barakakha** [Limbou/expandable_page_view#9]
When using ExpandablePageView as child of StatefulWidget and changing the list of children it fails on RangeError. 
the issue is that the _heights list is calculated in the initState() which is not called when Parent widget is updated. then when the user flip to a page in higher index it will fail on every place called _heights[index];

**Comment by Limbou** [comment]
Hi @barakakha, sorry for not responding for such a long time, I somehow missed an email about new issue. I fully understand the issue and will try to publish a fix this week.

**Comment by Limbou** [comment]
Fixed in #10
